### PR TITLE
high-scores: General updates

### PR DESCRIPTION
**Pull request by pgaspar**
Addressing some of the things mentioned in the comments.

### TODO:

- [x] Should we rename the exercise to `personal-bests`? (What's the process for that?)
- [x] Do we want to update other test descriptions or the readme to make things clearer?

### CODE REVIEW

**Comment by emcoding** [comment]
Hi @pgaspar !! So sorry for the delay.
This looks really good to me. I'd prefer the name High Scores, because in my mind that refers to games, where my association with personal best is sports. But I don't feel strongly about it.

**Review by emcoding — APPROVED** [review]

**Comment by emcoding** [comment]
I forgot: One thing that I'd like to add is a few lines for other maintainers, about the hint we added in the Ruby version, with the links to documentation and hints to what the exercise is about. 
I'll see if I can do that later today.

**Comment by emcoding** [comment]
Hi @pgaspar !
I'd like to add this to the canonical data:
```
#right after version 
"comments": [
    "This is meant to be an easy exercise to practise: ",
    "* arrays as simple lists",
    "* instantiating a class",
    "Consider adding a track specific recommendation in the track's hint.md.",
    "Consider linking to a explanatory blogpost or beginner level tutorials for both topics.",
    "See Ruby Track hint.md for an example."
  ],
```
As this is meant to be one of the first core exercises (in the Ruby Track): 
I hope to inspire maintainers to give some basic level directions to the Readme's for the early exercises, for two reasons:
- help students understand better what is expected 
- make mentoring faster/easier, because students got some explanation elsewhere
- (with the ultimate goal of making mentoring more consistent and more aligned with the level of the exercise )

So, I'd  like to add this as comments for the maintainers. But, if there's going to be lots of discussion about it, I don't think it should block progress and we can take it out.


What do you think?

**Comment by pgaspar** [comment]
Hey @F3PiX! I think it's ok. I'm not sure about the "See Ruby Track hint.md for an example." part, but maybe there's no problem there either.

I think it's worth a shot :+1:. Feel free to push those changes, I'll run the linter and make sure everything is good so we can open the PR afterwards.

**Comment by pgaspar** [comment]
@F3PiX also, what do you think about "Do we want to update other test descriptions or the readme to make things clearer?" in regards to the comments about this being a "personal" high score list?

**Comment by emcoding** [comment]
> "Do we want to update other test descriptions or the readme to make things clearer?" in regards to the comments about this being a "personal" high score list?

I had to read through the old comments, but you addressed the important points. I don't see much value in other changes, at the moment. Agree? Or...?

**Comment by pgaspar** [comment]
Ok, agree :+1:

**Comment by emcoding** [comment]
@pgaspar Added the comments! I'm happy. Again. :-)

**Comment by pgaspar** [comment]
@F3PiX all seems good to me :+1: Do you have time to open a PR for this? I'm a bit overwhelmed this week, but I can try doing it during the weekend.

**Comment by emcoding** [comment]
Thanks Pedro! I'll open the PR. Probably not today but soon :-)

**Comment by emcoding** [comment]
BTW. Usually, when working with PR's in a fork, I don't merge the branch into master, but pull the upstream master locally, than push master from local to my fork/master. 
I don't remember what kind of problems that prevents, but I remember that this was the recommended way.

**Comment by pgaspar** [comment]
@F3PiX yep, that's what I did! Github seems to mark that as a merge now. I pushed local to `pgaspar/master` and this PR was automatically closed with the "merged" message. It's smart because that's exactly what happened, although it was merged upstream.

**Comment by emcoding** [comment]
OOoh that's handy. Or confusing. Or both ;-)

**Pull request merged**
